/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary-container': '#131b2e',
        'outline-variant': '#c6c6cd',
        'on-secondary-fixed': '#0b1c30',
        'tertiary-fixed-dim': '#c4c7c9',
        'inverse-surface': '#263143',
        'primary-fixed': '#dae2fd',
        'on-tertiary': '#ffffff',
        secondary: '#505f76',
        'tertiary-fixed': '#e0e3e5',
        surface: '#f9f9ff',
        'surface-container-low': '#f0f3ff',
        'on-background': '#111c2d',
        'inverse-primary': '#bec6e0',
        'on-tertiary-container': '#818486',
        'error-container': '#ffdad6',
        outline: '#76777d',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'on-secondary-container': '#54647a',
        'inverse-on-surface': '#ecf1ff',
        'on-surface-variant': '#45464d',
        'secondary-container': '#d0e1fb',
        'surface-container': '#e7eeff',
        'surface-bright': '#f9f9ff',
        background: '#f9f9ff',
        'on-primary-fixed-variant': '#3f465c',
        'surface-container-high': '#dee8ff',
        'tertiary-container': '#191c1e',
        'on-surface': '#111c2d',
        'surface-container-highest': '#d8e3fb',
        'on-error': '#ffffff',
        'on-primary-container': '#7c839b',
        'on-primary': '#ffffff',
        'on-tertiary-fixed-variant': '#444749',
        'on-primary-fixed': '#131b2e',
        'secondary-fixed': '#d3e4fe',
        'on-secondary-fixed-variant': '#38485d',
        'surface-container-lowest': '#ffffff',
        primary: '#0F172A',
        'surface-tint': '#565e74',
        tertiary: '#000000',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-dim': '#cfdaf2',
        'on-error-container': '#93000a',
        'surface-variant': '#d8e3fb',
        'primary-fixed-dim': '#bec6e0',
        'on-tertiary-fixed': '#191c1e',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'unit-xl': '48px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
        'unit-xs': '4px',
        'unit-lg': '24px',
        'unit-md': '16px',
        'unit-xxl': '80px',
        'container-max': '1280px',
        'unit-sm': '8px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', letterSpacing: '0em', fontWeight: '400' }],
        h3: ['24px', { lineHeight: '32px', letterSpacing: '0em', fontWeight: '600' }],
        'hero-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        h2: ['30px', { lineHeight: '38px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'hero-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        caption: ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}
